name: Rims
favicon: null
layout_spectrum: 0.4195816230494529
typography_spectrum: 0.11810382804833353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.44684145995415747
purpose:
  - name: follow
    item: null
    url: null
